[package]
name = "keket"
version = "0.4.0"
edition = "2021"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
description = "Database-like Asset management on top of ECS storage"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/keket"
repository = "https://github.com/PsichiX/keket"
documentation = "https://docs.rs/keket"
readme = "../../README.md"

[dependencies]
anput = "0.6"

[dev-dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
zip = "2"
