[package]
name = "keket"
version = "0.10.1"
edition = "2021"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
description = "Database-like Asset management on top of ECS storage"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/keket"
repository = "https://github.com/PsichiX/keket"
documentation = "https://docs.rs/keket"
readme = "../../README.md"

[features]
default = ["hotreload"]
hotreload = ["notify"]

[dependencies]
anput = "0.6"
serde = { version = "1", features = ["derive"] }
notify = { version = "8.0", optional = true }

[dev-dependencies]
serde_json = "1"
zip = "2"
